//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.IoTSuite.Connectedfactory.WebApp.App_GlobalResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Action has executed...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ActionDetailResultExecuting {
            get {
                return ResourceManager.GetString("ActionDetailResultExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div&gt;Instructions for Windows can be found &lt;a target=&quot;_blank&quot; style=&quot;text-decoration:underline&quot; href=&quot;https://go.microsoft.com/fwlink/p/?linkid=846367&quot;&gt;here&lt;/a&gt;.&lt;/div&gt;
        ///&lt;div&gt;Instructions for Linux be found &lt;a target=&quot;_blank&quot; style=&quot;text-decoration:underline&quot; href=&quot;https://go.microsoft.com/fwlink/p/?linkid=846368&quot;&gt;here&lt;/a&gt;.&lt;/div&gt; &lt;div&gt;Instructions for editing assembly line information can be found &lt;a target=&quot;_blank&quot; style=&quot;text-decoration:underline&quot; href=&quot;https://go.microsoft.com/fwlink/p/?linkid=846688&quot;&gt;her[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddGatewayBodyPoint1 {
            get {
                return ResourceManager.GetString("AddGatewayBodyPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect your own gateway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddGatewayTitle {
            get {
                return ResourceManager.GetString("AddGatewayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Administrator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AdministratorRole {
            get {
                return ResourceManager.GetString("AdministratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acknowledge alert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertActionAcknowledge {
            get {
                return ResourceManager.GetString("AlertActionAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert successfully acknowledged.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertActionAcknowledgeSuccessful {
            get {
                return ResourceManager.GetString("AlertActionAcknowledgeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close alert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertActionClose {
            get {
                return ResourceManager.GetString("AlertActionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert successfully closed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertActionCloseSuccessful {
            get {
                return ResourceManager.GetString("AlertActionCloseSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertActionExecute {
            get {
                return ResourceManager.GetString("AlertActionExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check content in a new browser tab/window.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertActionWebPageOpened {
            get {
                return ResourceManager.GetString("AlertActionWebPageOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert cause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDescription {
            get {
                return ResourceManager.GetString("AlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetails {
            get {
                return ResourceManager.GetString("AlertDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action result:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsActionResultHeader {
            get {
                return ResourceManager.GetString("AlertDetailsActionResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsDescriptionHeader {
            get {
                return ResourceManager.GetString("AlertDetailsDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsLocationHeader {
            get {
                return ResourceManager.GetString("AlertDetailsLocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Action defined과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsNoActionAvailable {
            get {
                return ResourceManager.GetString("AlertDetailsNoActionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Occurences:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsOccurencesHeader {
            get {
                return ResourceManager.GetString("AlertDetailsOccurencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click chart to explore in Azure Time Series Insights과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsRdxLinkHeader {
            get {
                return ResourceManager.GetString("AlertDetailsRdxLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsTimeHeader {
            get {
                return ResourceManager.GetString("AlertDetailsTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertDetailsUnknown {
            get {
                return ResourceManager.GetString("AlertDetailsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The alert information is no longer available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertIdUnknown {
            get {
                return ResourceManager.GetString("AlertIdUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of products above maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertKpi1AboveMaximum {
            get {
                return ResourceManager.GetString("AlertKpi1AboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of products below minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertKpi1BelowMinimum {
            get {
                return ResourceManager.GetString("AlertKpi1BelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Energy consumption above maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertKpi2AboveMaximum {
            get {
                return ResourceManager.GetString("AlertKpi2AboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Energy consumption below minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertKpi2BelowMinimum {
            get {
                return ResourceManager.GetString("AlertKpi2BelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertNode {
            get {
                return ResourceManager.GetString("AlertNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Availability above maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeeAvailabilityAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeAvailabilityAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Availability below minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeeAvailabilityBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeAvailabilityBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Overall above maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeeOverallAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeOverallAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Overall below minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeeOverallBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeOverallBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Performance above maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeePerformanceAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeePerformanceAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Performance below minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeePerformanceBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeePerformanceBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Quality above maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeeQualityAboveMaximum {
            get {
                return ResourceManager.GetString("AlertOeeQualityAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OEE Qualty below minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertOeeQualityBelowMinimum {
            get {
                return ResourceManager.GetString("AlertOeeQualityBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Production line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertProductionLine {
            get {
                return ResourceManager.GetString("AlertProductionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertsContainerHeader {
            get {
                return ResourceManager.GetString("AlertsContainerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose action:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertSelectAction {
            get {
                return ResourceManager.GetString("AlertSelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Station과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertStation {
            get {
                return ResourceManager.GetString("AlertStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value above maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertValueAboveMaximum {
            get {
                return ResourceManager.GetString("AlertValueAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value below minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlertValueBelowMinimum {
            get {
                return ResourceManager.GetString("AlertValueBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while processing your request.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading data from Azure Time Series Insights과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnimationTimeSeriesLoading {
            get {
                return ResourceManager.GetString("AnimationTimeSeriesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error accessing certificate for download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserCertDownloadError {
            get {
                return ResourceManager.GetString("BrowserCertDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection status:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserCommunicationStatusMessageLabel {
            get {
                return ResourceManager.GetString("BrowserCommunicationStatusMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserConnect {
            get {
                return ResourceManager.GetString("BrowserConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected to OPC server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserConnectedTo {
            get {
                return ResourceManager.GetString("BrowserConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error while connecting to the OPC UA server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserConnectErrorHeader {
            get {
                return ResourceManager.GetString("BrowserConnectErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception while trying to connect to the OPC UA server.
        ///Exceptionmessage:
        ///{0}
        ///Inner Message:
        ///{1}
        ///Stack trace:
        ///{2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserConnectException {
            get {
                return ResourceManager.GetString("BrowserConnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserConnecting {
            get {
                return ResourceManager.GetString("BrowserConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attributes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelHeaderAttributes {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method call과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelHeaderMethod {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelHeaderPublish {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read variable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelHeaderRead {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpublish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelHeaderUnpublish {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderUnpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write variable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelHeaderWrite {
            get {
                return ResourceManager.GetString("BrowserContextPanelHeaderWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publishing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelPublishing {
            get {
                return ResourceManager.GetString("BrowserContextPanelPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpublishing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserContextPanelUnPublishing {
            get {
                return ResourceManager.GetString("BrowserContextPanelUnPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserDisconnectButton {
            get {
                return ResourceManager.GetString("BrowserDisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception while trying to disconnect to the OPC UA server.
        ///Exceptionmessage:
        ///{0}
        ///Inner Message:
        ///{1}
        ///Stack trace:
        ///{2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserDisconnectException {
            get {
                return ResourceManager.GetString("BrowserDisconnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserDontTrustButton {
            get {
                return ResourceManager.GetString("BrowserDontTrustButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download certificate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserDownload {
            get {
                return ResourceManager.GetString("BrowserDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should your OPC UA server require a manual installation of client certificates, you can download this website&apos;s OPC UA certificate here:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserDownloadText {
            get {
                return ResourceManager.GetString("BrowserDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After you have connected your gateway, you can start connecting your own OPC UA servers. Enter your OPC UA server&apos;s endpoint URL (opc.tcp://servername.domain:portnumber) here:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserEnterOwn {
            get {
                return ResourceManager.GetString("BrowserEnterOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser error:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserError {
            get {
                return ResourceManager.GetString("BrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserErrorContinueButton {
            get {
                return ResourceManager.GetString("BrowserErrorContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error message:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserErrorMessage {
            get {
                return ResourceManager.GetString("BrowserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserErrorServer {
            get {
                return ResourceManager.GetString("BrowserErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occured during browsing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserErrorUnknown {
            get {
                return ResourceManager.GetString("BrowserErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Any과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcAttributesAny {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OneDimension과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcAttributesOneDimension {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesOneDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OneOrMoreDimensions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcAttributesOneOrMoreDimensions {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesOneOrMoreDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scalar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcAttributesScalar {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesScalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScalarOrOneDimension과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcAttributesScalarOrOneDimension {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesScalarOrOneDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TwoDimensions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcAttributesTwoDimensions {
            get {
                return ResourceManager.GetString("BrowserOpcAttributesTwoDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnostic info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcDataDiagnosticInfoLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataDiagnosticInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server timestamp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcDataServerTimestampLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataServerTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source timestamp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcDataSourceTimestampLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataSourceTimestampLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcDataStatusLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcDataValueLabel {
            get {
                return ResourceManager.GetString("BrowserOpcDataValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error while accessing the OPC UA server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcErrorHeader {
            get {
                return ResourceManager.GetString("BrowserOpcErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occured while trying to access the OPC UA server.
        ///Exceptionmessage:
        ///{0}
        ///Inner message:
        ///{1}
        ///Stack trace:
        ///{2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcException {
            get {
                return ResourceManager.GetString("BrowserOpcException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method call failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcMethodCallFailed {
            get {
                return ResourceManager.GetString("BrowserOpcMethodCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method call succeeded과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcMethodCallSucceeded {
            get {
                return ResourceManager.GetString("BrowserOpcMethodCallSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method call succeeded and returned the following results:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcMethodCallSucceededWithResults {
            get {
                return ResourceManager.GetString("BrowserOpcMethodCallSucceededWithResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcMethodStatusCode {
            get {
                return ResourceManager.GetString("BrowserOpcMethodStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continuous과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueContinuous {
            get {
                return ResourceManager.GetString("BrowserOpcValueContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueHistory {
            get {
                return ResourceManager.GetString("BrowserOpcValueHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueHistoryUpdate {
            get {
                return ResourceManager.GetString("BrowserOpcValueHistoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indeterminate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueIndeterminate {
            get {
                return ResourceManager.GetString("BrowserOpcValueIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueNoAccess {
            get {
                return ResourceManager.GetString("BrowserOpcValueNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Readable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueReadable {
            get {
                return ResourceManager.GetString("BrowserOpcValueReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subscribe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueSubscribe {
            get {
                return ResourceManager.GetString("BrowserOpcValueSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueUnknown {
            get {
                return ResourceManager.GetString("BrowserOpcValueUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writeable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcValueWriteable {
            get {
                return ResourceManager.GetString("BrowserOpcValueWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;font color=&quot;red&quot;&gt;Error: Conversion of the value &apos;{0}&apos; to type &apos;{1}&apos; is not possible. (Details: {2})&lt;/font&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserOpcWriteConversionProblem {
            get {
                return ResourceManager.GetString("BrowserOpcWriteConversionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a server from the preconfigured list:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserPreconfiguredListLabel {
            get {
                return ResourceManager.GetString("BrowserPreconfiguredListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Root과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserRootNodeName {
            get {
                return ResourceManager.GetString("BrowserRootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserSecurityWarning {
            get {
                return ResourceManager.GetString("BrowserSecurityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect your own OPC UA server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserSelectNewServer {
            get {
                return ResourceManager.GetString("BrowserSelectNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select an OPC UA server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserSelectServer {
            get {
                return ResourceManager.GetString("BrowserSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This might mean that someone&apos;s trying to fool you or steal information you send to the server. You should proceed only if you expected this issue, e.g. because you are using self-signed certificates with your server (not recommended).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserTrust {
            get {
                return ResourceManager.GetString("BrowserTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proceed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserTrustButton {
            get {
                return ResourceManager.GetString("BrowserTrustButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The certificate of the server you want to connect to cannot be verified.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserTrustHeader {
            get {
                return ResourceManager.GetString("BrowserTrustHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should only proceed if you are sure you wish to make this change.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserWriteWarning {
            get {
                return ResourceManager.GetString("BrowserWriteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This change will alter how your production line is configured.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BrowserWriteWarningHeader {
            get {
                return ResourceManager.GetString("BrowserWriteWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Factory Locations과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenFactoryListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenFactoryListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CURRENT PRODUCTION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenFactoryListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenFactoryListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOCATION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenFactoryListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenFactoryListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenFactoryListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenFactoryListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenOpcUaNodeListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VALUE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenOpcUaNodeListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NAME과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenOpcUaNodeListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenOpcUaNodeListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WARNING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenOpcUaNodeListListHeaderWarning {
            get {
                return ResourceManager.GetString("ChildrenOpcUaNodeListListHeaderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenProductionLineListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CURRENT CONFIGURATION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenProductionLineListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LINE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenProductionLineListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenProductionLineListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenProductionLineListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenStationListContainerHeaderPostfix {
            get {
                return ResourceManager.GetString("ChildrenStationListContainerHeaderPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CURRENT CONFIGURATION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenStationListListHeaderDetails {
            get {
                return ResourceManager.GetString("ChildrenStationListListHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenStationListListHeaderLocation {
            get {
                return ResourceManager.GetString("ChildrenStationListListHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChildrenStationListListHeaderStatus {
            get {
                return ResourceManager.GetString("ChildrenStationListListHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected factory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultSolutionName {
            get {
                return ResourceManager.GetString("DefaultSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occured while accessing the website.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorAccessProblem {
            get {
                return ResourceManager.GetString("ErrorAccessProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not a valid node or station과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorGetDataForOpcUaNode {
            get {
                return ResourceManager.GetString("ErrorGetDataForOpcUaNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not a valid node과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorGetOeeKpiData {
            get {
                return ResourceManager.GetString("ErrorGetOeeKpiData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have insufficient permissions for this operation. Please check with the administrator of this site.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorInsufficientPermissions {
            get {
                return ResourceManager.GetString("ErrorInsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FilterApply {
            get {
                return ResourceManager.GetString("FilterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphFriday {
            get {
                return ResourceManager.GetString("GraphFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LAST 24 HOURS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphLastDay {
            get {
                return ResourceManager.GetString("GraphLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LAST HOUR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphLastHour {
            get {
                return ResourceManager.GetString("GraphLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LAST 7 DAYS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphLastWeek {
            get {
                return ResourceManager.GetString("GraphLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Threshold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphMaxThreshold {
            get {
                return ResourceManager.GetString("GraphMaxThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Threshold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphMinThreshold {
            get {
                return ResourceManager.GetString("GraphMinThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphMonday {
            get {
                return ResourceManager.GetString("GraphMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on graph to explore in Azure Time Series Insights과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphRDXLinkHeader {
            get {
                return ResourceManager.GetString("GraphRDXLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sa과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphSaturday {
            get {
                return ResourceManager.GetString("GraphSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Su과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphSunday {
            get {
                return ResourceManager.GetString("GraphSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Th과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphThursday {
            get {
                return ResourceManager.GetString("GraphThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphTuesday {
            get {
                return ResourceManager.GetString("GraphTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GraphWednesday {
            get {
                return ResourceManager.GetString("GraphWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Implicit Read-Only과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImplicitReadOnlyRole {
            get {
                return ResourceManager.GetString("ImplicitReadOnlyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://azure.microsoft.com/solutions/iot-suite/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoIconLink {
            get {
                return ResourceManager.GetString("InfoIconLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IoT Suite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IoTSuite {
            get {
                return ResourceManager.GetString("IoTSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Units per hour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Kpi1Label {
            get {
                return ResourceManager.GetString("Kpi1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kWh per hour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Kpi2Label {
            get {
                return ResourceManager.GetString("Kpi2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Performance Indicators과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KpiContainerLabel {
            get {
                return ResourceManager.GetString("KpiContainerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KpiMaximum {
            get {
                return ResourceManager.GetString("KpiMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KpiMinimum {
            get {
                return ResourceManager.GetString("KpiMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KpiTarget {
            get {
                return ResourceManager.GetString("KpiTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last day (hours)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LastDayHistoryGraphXlabel {
            get {
                return ResourceManager.GetString("LastDayHistoryGraphXlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last hour (minutes)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LastHourHistoryGraphXlabel {
            get {
                return ResourceManager.GetString("LastHourHistoryGraphXlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last week (days)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LastWeekHistoryGraphXlabel {
            get {
                return ResourceManager.GetString("LastWeekHistoryGraphXlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help &amp; Support과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LinkLabelHelpAndSupport {
            get {
                return ResourceManager.GetString("LinkLabelHelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give feedback과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LinkLabelHelpGiveFeedback {
            get {
                return ResourceManager.GetString("LinkLabelHelpGiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Azure IoT Suite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MicrosoftAzureIoTSuite {
            get {
                return ResourceManager.GetString("MicrosoftAzureIoTSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Gateway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NavigationMenuAddGateway {
            get {
                return ResourceManager.GetString("NavigationMenuAddGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add my OPC Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NavigationMenuAddServer {
            get {
                return ResourceManager.GetString("NavigationMenuAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NavigationMenuBrowser {
            get {
                return ResourceManager.GetString("NavigationMenuBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NavigationMenuDashboard {
            get {
                return ResourceManager.GetString("NavigationMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Actions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NavigationMenuItemActions {
            get {
                return ResourceManager.GetString("NavigationMenuItemActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Menu Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NavigationMenuSidebarSizeToggle {
            get {
                return ResourceManager.GetString("NavigationMenuSidebarSizeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Factory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewFactoryName {
            get {
                return ResourceManager.GetString("NewFactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Production Line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewProductionLineName {
            get {
                return ResourceManager.GetString("NewProductionLineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Station과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewStationName {
            get {
                return ResourceManager.GetString("NewStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data series available for this item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoDataSeries {
            get {
                return ResourceManager.GetString("NoDataSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attribute of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeAttribute {
            get {
                return ResourceManager.GetString("NodeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attributes...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeAttributeRead {
            get {
                return ResourceManager.GetString("NodeAttributeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Call과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeButtonCall {
            get {
                return ResourceManager.GetString("NodeButtonCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeButtonWrite {
            get {
                return ResourceManager.GetString("NodeButtonWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Call...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeCall {
            get {
                return ResourceManager.GetString("NodeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calling method과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeCallingMethod {
            get {
                return ResourceManager.GetString("NodeCallingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Call in progress ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeCallInProgress {
            get {
                return ResourceManager.GetString("NodeCallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info on과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeInfo {
            get {
                return ResourceManager.GetString("NodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeLabelAccess {
            get {
                return ResourceManager.GetString("NodeLabelAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeLabelDescription {
            get {
                return ResourceManager.GetString("NodeLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miscellaneous:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeLabelMisc {
            get {
                return ResourceManager.GetString("NodeLabelMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node details:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeLabelNodeDetails {
            get {
                return ResourceManager.GetString("NodeLabelNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeLabelType {
            get {
                return ResourceManager.GetString("NodeLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeLabelValue {
            get {
                return ResourceManager.GetString("NodeLabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter are not supported yet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeMethodMessage {
            get {
                return ResourceManager.GetString("NodeMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MethodName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeMethodName {
            get {
                return ResourceManager.GetString("NodeMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Method has no parameter.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeMethodNoParameter {
            get {
                return ResourceManager.GetString("NodeMethodNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result of calling method과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeMethodResult {
            get {
                return ResourceManager.GetString("NodeMethodResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press button to call method.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodePressButton {
            get {
                return ResourceManager.GetString("NodePressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publish...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodePublish {
            get {
                return ResourceManager.GetString("NodePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publish in progress...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodePublishInProgress {
            get {
                return ResourceManager.GetString("NodePublishInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeRead {
            get {
                return ResourceManager.GetString("NodeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read in progress ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeReadInProgress {
            get {
                return ResourceManager.GetString("NodeReadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpublish...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeUnpublish {
            get {
                return ResourceManager.GetString("NodeUnpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpublish in progress...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeUnpublishInProgress {
            get {
                return ResourceManager.GetString("NodeUnpublishInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeUpdate {
            get {
                return ResourceManager.GetString("NodeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VariableName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeVariableName {
            get {
                return ResourceManager.GetString("NodeVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeWrite {
            get {
                return ResourceManager.GetString("NodeWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current value:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeWriteCurrentValue {
            get {
                return ResourceManager.GetString("NodeWriteCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write in progress ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeWriteInProgress {
            get {
                return ResourceManager.GetString("NodeWriteInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New value:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeWriteNewValue {
            get {
                return ResourceManager.GetString("NodeWriteNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result of writing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NodeWriteResult {
            get {
                return ResourceManager.GetString("NodeWriteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoFilterApplied {
            get {
                return ResourceManager.GetString("NoFilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JavaScript Required과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoJScriptHeader {
            get {
                return ResourceManager.GetString("NoJScriptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your browser is currently set to block JavaScript. You need to allow JavaScript to use this service.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoJScriptInfo1 {
            get {
                return ResourceManager.GetString("NoJScriptInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To learn how to allow JavaScript or to find out whether your browser supports JavaScript, check the online help in your web browser.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoJScriptInfo2 {
            get {
                return ResourceManager.GetString("NoJScriptInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Availability과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OeeAvailabilityLabel {
            get {
                return ResourceManager.GetString("OeeAvailabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overall Equipment Efficiency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OeeHeaderLabel {
            get {
                return ResourceManager.GetString("OeeHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overall Efficiency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OeeOverallLabel {
            get {
                return ResourceManager.GetString("OeeOverallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OeePerformanceLabel {
            get {
                return ResourceManager.GetString("OeePerformanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quality과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OeeQualityLabel {
            get {
                return ResourceManager.GetString("OeeQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception while initializing OPC UA stack. Error: {0} Inner: {1} Stack: {2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpcStackInitError {
            get {
                return ResourceManager.GetString("OpcStackInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read-Only과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReadOnlyRole {
            get {
                return ResourceManager.GetString("ReadOnlyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not establish connection to Publisher과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SessionNull {
            get {
                return ResourceManager.GetString("SessionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect gateway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleAddGateway {
            get {
                return ResourceManager.GetString("TitleAddGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect OPC UA server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleAddOpcServer {
            get {
                return ResourceManager.GetString("TitleAddOpcServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleBrowser {
            get {
                return ResourceManager.GetString("TitleBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TitleDashboard {
            get {
                return ResourceManager.GetString("TitleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View in Time Series Insights과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tsilink {
            get {
                return ResourceManager.GetString("Tsilink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UntrustedCertificate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UntrustedCertificate {
            get {
                return ResourceManager.GetString("UntrustedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must be signed in to continue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string YouMustBeSignedIn {
            get {
                return ResourceManager.GetString("YouMustBeSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you were signed in, your session has expired.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string YourSessionMayHaveExpired {
            get {
                return ResourceManager.GetString("YourSessionMayHaveExpired", resourceCulture);
            }
        }
    }
}
